package abc.parser;

public enum AbcGrammar {
    ROOT, HEADER, MUSIC, NUMBER, TITLE, VOICE, KEYFIELD, KEY, KEYNOTE, EYACCIDENTAL, METERFRACTION, ELEMENT, NOTEELEMENT, NOTE, NOTEORREST, PITCH, OCTAVE,
    NOTELENGTH, ACCIDENTAL, BASENOTE, REST, MIDTUNEFIELD, WHITESPACE, COMMENT, DIGIT, OTHERS, TEXT, NOTELENGTHSTRICT, TEMPOFIELD, LINE, COMPOSER, 
    DEFAULTLENGTH, METERFIELD, METER, TEMPO
}